virtual_clusters:
  - name: no-auth
    backend_cluster_name: kafka-localhost
    route_by:
      type: port
      port:
        listen_start: 19092
        min_broker_id: 1
    authentication:
      - type: anonymous
        mediation:
          type: anonymous
  - name: secured
    backend_cluster_name: kafka-localhost
    route_by:
      type: port
      port:
        listen_start: 29092
        min_broker_id: 1
    authentication:
      - type: sasl_oauth_bearer
        sasl_oauth_bearer:
          jwks:
            endpoint: http://localhost:8080/realms/kafka-realm/protocol/openid-connect/certs
            refresh: "1s"
        mediation:
          type: anonymous
backend_clusters:
  - name: kafka-localhost
    bootstrap_servers:
      - localhost:9092