contexts:
    default:
      brokers:
        - localhost:9092
    core-proxy:
      brokers:
        - localhost:19092
    team-a:
      brokers:
        - localhost:19192
    team-b:
      brokers:
        - localhost:19292
    team-b-authed:
      brokers:
        - localhost:19292
      sasl:
        enabled: true
        username: team-b-user
        password: secret
    team-b-schema:
      brokers:
        - localhost:19292
      sasl:
        enabled: true
        username: team-b-user
        password: secret
      schemaRegistry:
        url: http://localhost:8080/apis/ccompat/v7
